# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [17]:
cd /content/gdrive/My Drive/Colab Notebooks/MachineLearning/KNN

/content/gdrive/My Drive/Colab Notebooks/MachineLearning/KNN


## Importing the dataset

In [40]:
dataset1 = pd.read_csv('Iris.csv')

In [41]:
dataset = dataset1.drop(['SepalLengthCm','SepalWidthCm'],axis = 1)

In [42]:
dataset.head()

Id  PetalLengthCm  PetalWidthCm      Species
0   1            1.4           0.2  Iris-setosa
1   2            1.4           0.2  Iris-setosa
2   3            1.3           0.2  Iris-setosa
3   4            1.5           0.2  Iris-setosa
4   5            1.4           0.2  Iris-setosa

## Splitting the dataset into the Training set and Test set

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [44]:
print(X_train)

[[6.20e+01 5.90e+00 3.00e+00 4.20e+00 1.50e+00]
 [9.30e+01 5.80e+00 2.60e+00 4.00e+00 1.20e+00]
 [1.13e+02 6.80e+00 3.00e+00 5.50e+00 2.10e+00]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [1.42e+02 6.90e+00 3.10e+00 5.10e+00 2.30e+00]
 [4.40e+01 5.00e+00 3.50e+00 1.60e+00 6.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [6.10e+01 5.00e+00 2.00e+00 3.50e+00 1.00e+00]
 [1.17e+02 6.50e+00 3.00e+00 5.50e+00 1.80e+00]
 [1.45e+02 6.70e+00 3.30e+00 5.70e+00 2.50e+00]
 [1.20e+02 6.00e+00 2.20e+00 5.00e+00 1.50e+00]
 [1.09e+02 6.70e+00 2.50e+00 5.80e+00 1.80e+00]
 [7.00e+01 5.60e+00 2.50e+00 3.90e+00 1.10e+00]
 [1.36e+02 7.70e+00 3.00e+00 6.10e+00 2.30e+00]
 [5.70e+01 6.30e+00 3.30e+00 4.70e+00 1.60e+00]
 [8.10e+01 5.50e+00 2.40e+00 3.80e+00 1.10e+00]
 [1.24e+02 6.30e+00 2.70e+00 4.90e+00 1.80e+00]
 [1.34e+02 6.30e+00 2.80e+00 5.10e+00 1.50e+00]
 [1.07e+02 4.90e+00 2.50e+00 4.50e+00 1.70e+00]
 [1.47e+02 6.30e+00 2.50e+00 5.00e+00 1.90e+00]
 [5.10e+01 7.00e+00 3.20e+00 4.70e+00 1.

In [45]:
print(y_train)

['Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'

In [46]:
print(X_test)

[[1.15e+02 5.80e+00 2.80e+00 5.10e+00 2.40e+00]
 [6.30e+01 6.00e+00 2.20e+00 4.00e+00 1.00e+00]
 [3.40e+01 5.50e+00 4.20e+00 1.40e+00 2.00e-01]
 [1.08e+02 7.30e+00 2.90e+00 6.30e+00 1.80e+00]
 [8.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [1.01e+02 6.30e+00 3.30e+00 6.00e+00 2.50e+00]
 [4.10e+01 5.00e+00 3.50e+00 1.30e+00 3.00e-01]
 [8.70e+01 6.70e+00 3.10e+00 4.70e+00 1.50e+00]
 [7.70e+01 6.80e+00 2.80e+00 4.80e+00 1.40e+00]
 [7.20e+01 6.10e+00 2.80e+00 4.00e+00 1.30e+00]
 [1.35e+02 6.10e+00 2.60e+00 5.60e+00 1.40e+00]
 [5.20e+01 6.40e+00 3.20e+00 4.50e+00 1.50e+00]
 [7.40e+01 6.10e+00 2.80e+00 4.70e+00 1.20e+00]
 [5.50e+01 6.50e+00 2.80e+00 4.60e+00 1.50e+00]
 [6.40e+01 6.10e+00 2.90e+00 4.70e+00 1.40e+00]
 [3.80e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [7.90e+01 6.00e+00 2.90e+00 4.50e+00 1.50e+00]
 [9.10e+01 5.50e+00 2.60e+00 4.40e+00 1.20e+00]
 [4.60e+01 4.80e+00 3.00e+00 1.40e+00 3.00e-01]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.22e+02 5.60e+00 2.80e+00 4.90e+00 2.

In [47]:
print(y_test)

['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor']


## Feature Scaling

In [48]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) #avoid data leakage

In [49]:
print(X_train)

[[-3.41283725e-01  1.54399532e-02 -1.19254753e-01  2.25126850e-01
   3.56381749e-01]
 [ 3.50852428e-01 -9.98450310e-02 -1.04039491e+00  1.13559562e-01
  -2.86480506e-02]
 [ 7.97391882e-01  1.05300481e+00 -1.19254753e-01  9.50314227e-01
   1.12644135e+00]
 [-1.65857511e+00 -1.36797986e+00  3.41315328e-01 -1.39259884e+00
  -1.31208072e+00]
 [ 1.44487409e+00  1.16828980e+00  1.11030287e-01  7.27179649e-01
   1.38312788e+00]
 [-7.43169234e-01 -1.02212490e+00  1.03217045e+00 -1.22524790e+00
  -7.98707650e-01]
 [-1.47995933e+00 -5.60984968e-01  1.49274053e+00 -1.28103155e+00
  -1.31208072e+00]
 [-3.63610698e-01 -1.02212490e+00 -2.42210516e+00 -1.65358660e-01
  -2.85334584e-01]
 [ 8.86699773e-01  7.07149859e-01 -1.19254753e-01  9.50314227e-01
   7.41411549e-01]
 [ 1.51185501e+00  9.37719827e-01  5.71600368e-01  1.06188152e+00
   1.63981441e+00]
 [ 9.53680691e-01  1.30724937e-01 -1.96153508e+00  6.71396005e-01
   3.56381749e-01]
 [ 7.08083991e-01  9.37719827e-01 -1.27067995e+00  1.11766516e+00

In [50]:
print(X_test.dtype)

float64


## Training the K-NN model on the Training set

In [51]:
from math import sqrt
class KNN():
  def __init__(self,k):
    self.k=k
    print(self.k)
  def fit(self,X_train,y_train):
    self.x_train=X_train
    self.y_train=y_train
  def calculate_euclidean(self,sample1,sample2):
    distance=0.0
    for i in range(len(sample1)):
      distance+=(sample1[i]-sample2[i])**2 #Euclidean Distance = sqrt(sum i to N (x1_i – x2_i)^2)
    return sqrt(distance)
  def nearest_neighbors(self,test_sample):
    distances=[]#calculate distances from a test sample to every sample in a training set
    for i in range(len(self.x_train)):
      distances.append((self.y_train[i],self.calculate_euclidean(self.x_train[i],test_sample)))
    distances.sort(key=lambda x:x[1])#sort in ascending order, based on a distance value
    neighbors=[]
    for i in range(self.k): #get first k samples
      neighbors.append(distances[i][0])
    return neighbors
  def predict(self,test_set):
    predictions=[]
    for test_sample in test_set:
      neighbors=self.nearest_neighbors(test_sample)
      labels=[sample for sample in neighbors]
      prediction=max(labels,key=labels.count)
      predictions.append(prediction)
    return predictions


In [52]:
model=KNN(5) #our model
model.fit(X_train,y_train)

5


In [53]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)#The default metric is minkowski, and with p=2 is equivalent to the standard Euclidean metric.
classifier.fit(X_train, y_train)

KNeighborsClassifier()

## Predicting the Test set results

In [54]:
y_pred = classifier.predict(X_test)

In [55]:
predictions=model.predict(X_test)#our model's predictions

## Making the Confusion Matrix to compare both models

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]


1.0

In [57]:
cm = confusion_matrix(y_test, predictions) #our model
print(cm)
accuracy_score(y_test, predictions)

[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]


1.0

## Visualising the Test set results 

In [58]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 1),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 1))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN (Test set)')
plt.xlabel('PetalLengthCm')
plt.ylabel('PetalWidthCm')
plt.legend()
plt.show()

ValueError: ignored